// <auto-generated />
namespace Alexandria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DIAGRAMA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DIAGRAMA));
        
        string IMigrationMetadata.Id
        {
            get { return "202002080610264_DIAGRAMA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
